// Code generated by gonstructor --type=StructureWithInitBuz --constructorTypes=allArgs,builder --init initializeWithError -propagateInitFuncReturns; DO NOT EDIT.

package init_return_propagation

func NewStructureWithInitBuz(foo string) (*StructureWithInitBuz, error) {
	r := &StructureWithInitBuz{
		foo: foo,
	}

	ret_initializeWithError0 := r.initializeWithError()

	return r, ret_initializeWithError0
}

type StructureWithInitBuzBuilder struct {
	foo string
}

func NewStructureWithInitBuzBuilder() *StructureWithInitBuzBuilder {
	return &StructureWithInitBuzBuilder{}
}

func (b *StructureWithInitBuzBuilder) Foo(foo string) *StructureWithInitBuzBuilder {
	b.foo = foo
	return b
}

func (b *StructureWithInitBuzBuilder) Build() (*StructureWithInitBuz, error) {
	r := &StructureWithInitBuz{
		foo: b.foo,
	}
	ret_initializeWithError0 := r.initializeWithError()
	return r, ret_initializeWithError0
}
