// Code generated by gonstructor --type=StructureWithInitFoo --constructorTypes=allArgs,builder --init initialize -propagateInitFuncReturns; DO NOT EDIT.

package init_return_propagation

func NewStructureWithInitFoo(foo string) *StructureWithInitFoo {
	r := &StructureWithInitFoo{
		foo: foo,
	}

	r.initialize()

	return r
}

type StructureWithInitFooBuilder struct {
	foo string
}

func NewStructureWithInitFooBuilder() *StructureWithInitFooBuilder {
	return &StructureWithInitFooBuilder{}
}

func (b *StructureWithInitFooBuilder) Foo(foo string) *StructureWithInitFooBuilder {
	b.foo = foo
	return b
}

func (b *StructureWithInitFooBuilder) Build() *StructureWithInitFoo {
	r := &StructureWithInitFoo{
		foo: b.foo,
	}
	r.initialize()
	return r
}
