// Code generated by gonstructor --type=StructureWithInitQux --constructorTypes=allArgs,builder --init initializeWithMultipleReturns -propagateInitFuncReturns; DO NOT EDIT.

package init_return_propagation

func NewStructureWithInitQux(foo string) (*StructureWithInitQux, *string, error) {
	r := &StructureWithInitQux{
		foo: foo,
	}

	ret_initializeWithMultipleReturns0, ret_initializeWithMultipleReturns1 := r.initializeWithMultipleReturns()

	return r, ret_initializeWithMultipleReturns0, ret_initializeWithMultipleReturns1
}

type StructureWithInitQuxBuilder struct {
	foo string
}

func NewStructureWithInitQuxBuilder() *StructureWithInitQuxBuilder {
	return &StructureWithInitQuxBuilder{}
}

func (b *StructureWithInitQuxBuilder) Foo(foo string) *StructureWithInitQuxBuilder {
	b.foo = foo
	return b
}

func (b *StructureWithInitQuxBuilder) Build() (*StructureWithInitQux, *string, error) {
	r := &StructureWithInitQux{
		foo: b.foo,
	}
	ret_initializeWithMultipleReturns0, ret_initializeWithMultipleReturns1 := r.initializeWithMultipleReturns()
	return r, ret_initializeWithMultipleReturns0, ret_initializeWithMultipleReturns1
}
