// Code generated by gonstructor --type=StructureWithInitBar --constructorTypes=allArgs,builder --init initializeWithActualValueReceiver -propagateInitFuncReturns; DO NOT EDIT.

package init_return_propagation

func NewStructureWithInitBar(foo string) *StructureWithInitBar {
	r := &StructureWithInitBar{
		foo: foo,
	}

	r.initializeWithActualValueReceiver()

	return r
}

type StructureWithInitBarBuilder struct {
	foo string
}

func NewStructureWithInitBarBuilder() *StructureWithInitBarBuilder {
	return &StructureWithInitBarBuilder{}
}

func (b *StructureWithInitBarBuilder) Foo(foo string) *StructureWithInitBarBuilder {
	b.foo = foo
	return b
}

func (b *StructureWithInitBarBuilder) Build() *StructureWithInitBar {
	r := &StructureWithInitBar{
		foo: b.foo,
	}
	r.initializeWithActualValueReceiver()
	return r
}
